### ISSUE TITLE
Standardise attribute names

### ISSUE THREAD

**Issue by LJWatson** [bkardell/common-panel#14]
We might want to standardise attribute names, and at the same time bring them in-line with existing HTML attribute names?

We currently have "is-removable", "expanded-state" and "preferred-display". Perhaps "removable", "expanded" and "display" would work - along the lines of "checked" and "selected" etc.?

**Comment by bkardell** [comment]
I think there is discrepancy within the spec, and definitely between spec and prototype about whether it is called "expansion-state" or "expanded-state"..  The key is that it cannot be a boolean, it needs to be "opened" or "closed" (currently the default if present but unspecified is "opened" and specified behavior exists if it is anything else).  This is all defined in 4.3...   But, yes, I think removable/expanded would work.  

Preferred-display is from another proposal and I don't think "display" works, we probably need thought on that one.  "preference" is probably better.

**Comment by LJWatson** [comment]
The latest draft of the spec uses `<panel>`, `<paneltitle>`, `<panelset>`, removable, expandable and prefereddisplay.
