### ISSUE TITLE
Missing alts on images

### ISSUE THREAD

**Issue by LJWatson** [bkardell/common-panel#2]
The images in panel.html need alt attributes/text.

**Comment by bkardell** [comment]
I struggled with how to do this well.  As it is defining a separation
between visual and useful, accessible structure, it's useful to show
presentational related things, as well as describe the structure.  The only
images in here are demonstrating without an implementation what something
might 'look' like visually.  What kind of alt text would I use to make that
helpful? I assumed that without alt text it would simply skip the image
which seemed ok to me, but I'm very open to direction, help or pull here.

**Comment by LJWatson** [comment]
If the images don't provide any information beyond what's in the text content, then a null alt can be used (alt=""). This will cause ATs to ignore the images completely. If the image doesn't have an alt attribute some ATs will announce the file path instead.

I'll add the alts in my next commit.

## 

@LeonieWatson Carpe diem

**Comment by bkardell** [comment]
I added on my last commit. Also removed panels.html and merged your changes
into index.html - apologies for confusion.
