### ISSUE TITLE
please merge the documents

### ISSUE THREAD

**Issue by chaals** [bkardell/common-panel#21]
There are two index docs, which is a bit frustrating for trying to figure out what's what. Can we merge them one way or another, and stick to just one please?

**Comment by bkardell** [comment]
we are in process of merging them, yes.

**Comment by chaals** [comment]
\o/

I'll hold off on my trivially-fixed issues and file them as pull requests then...

**Comment by LJWatson** [comment]
@chaals 
Done. index.src.html is now the default (and only) version.
