### ISSUE TITLE
Permissible for comics?

### ISSUE THREAD

**Issue by tigt** [bkardell/common-panel#30]
Would use of `<panelset>` and `<panel>` be permissible to mock up comic, well, panels? If the user paged through them it seems to be a similar conceit.

**Comment by LJWatson** [comment]
@Tigt 
Yes, that sounds like a good use case. Is there a particular visual metaphor (carousel, deck etc.) you think would be most suitable?

**Comment by tigt** [comment]
Deck. The only snag is that a `<panel>` would actually contain multiple
comic panels... But probably not a dealbreaker.

**Comment by LJWatson** [comment]
@Tigt 
Thanks. I'll add this as a use case to the spec. I don't think the multiple comic panels per `<panel>` is a problem - the ability to cycle through seems like the key thing.

**Comment by bkardell** [comment]
@LjWatson if you're interested http://codepen.io/Tigt/blog/how-do-you-mark-up-a-comic

**Comment by bkardell** [comment]
@Tigt I'd love to see what you might be able to do with the prollyfill - let me know if you want to try it out, I'd love to follow along/help resolve any snags.

**Comment by tigt** [comment]
@bkardell 
Certainly! I'm still working on the actual content of the comic, but I'll have to tech demo it at some point.

**Comment by LJWatson** [comment]
@Tigt 
I've added a use case for the deck metaphor. 
https://github.com/bkardell/common-panel/commit/f42c785f3a8d3d9cc9c63696979febb63f1ad439

**Comment by tigt** [comment]
Wonderful! I'll try fitting these elements i to my current Handlebars
tenplates and see how that goes
