### ISSUE TITLE
Keyboard nav/focus issue

### ISSUE THREAD

**Issue by bkardell** [bkardell/common-panel#35]
Currently keyboard handling is handled at the level of panelset itself in the prototypes and it currently does so regardless of which thing actually has focus - this means that if you press keys inside of panel content (up, down, left right) they are handled in terms of switching to the next or previous tab which is definitely not right.

**Comment by LJWatson** [comment]
Agreed. Once in the panel content it should not be possible to cycle to the prev/next panels.

Worth noting that with a Windows screen reader running, the keyboard navigation within the panel content is ignored anyway.

**Comment by bkardell** [comment]
resolved in the directive version, but https://github.com/bkardell/common-panel/issues/37 prevents truly closing this for sure because it's hard to test until that is addressed
